{
  "name": "olive-library-links-worker",
  "main": "index.js",
  "compatibility_date": "2025-04-10",
  "env": {
    "GOOGLE_CLIENT_EMAIL": "",
    "GOOGLE_PRIVATE_KEY": "",
    "GOOGLE_SHEET_ID": "",
    "GOOGLE_SHEET_RANGE": "Sheet1!A2:C"
  }
}
